### ISSUE TITLE
PostgreSQL version below 10 support

### ISSUE THREAD

**Issue by zilder** [adjust/pg-telemetry#16]
Documentation states that postgresql versions 9.6+ are supported, but starting with version 1.2 pgtelemetry uses column `pg_stat_activity.backend_type` which is only available in postgresql v10+.

**Comment by alexeyklyukin** [comment]
Yes, I removed support for pre-10 versions at https://github.com/adjust/pg-telemetry/commit/fc99c80532dade54f59ff7598263316633b5dd29 as it was too tedious to support both and there are very few chances it's used with 9.6 anywhere. 

I'll update the docs, thanks!

**Comment by alexeyklyukin** [comment]
And there we go https://github.com/adjust/pg-telemetry/pull/17
