### ISSUE TITLE
make installcheck fails

### ISSUE THREAD

**Issue by joelonsql** [adjust/pg-telemetry#19]
Hi,

Thanks for making pg-telemetry.

It looks like there is a problem with the tests:

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04.2 LTS
    Release:	20.04
    Codename:	focal

    $ psql --version
    psql (PostgreSQL) 13.2 (Ubuntu 13.2-1.pgdg20.04+1)

    $ make installcheck
    /usr/lib/postgresql/13/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/13/bin'    --dbname=contrib_regression definitions
    (using postmaster on Unix socket, default port)
    ============== dropping database "contrib_regression" ==============
    DROP DATABASE
    ============== creating database "contrib_regression" ==============
    CREATE DATABASE
    ALTER DATABASE
    ============== running regression test queries        ==============
    test definitions                  ... FAILED       30 ms

    ======================
    1 of 1 tests failed.
    ======================

    The differences that caused some tests to fail can be viewed in the
    file "/home/joel/postgresql-extensions/pg-telemetry/regression.diffs".  A copy of the test summary that you see
    above is saved in the file "/home/joel/postgresql-extensions/pg-telemetry/regression.out".

    make: *** [/usr/lib/postgresql/13/lib/pgxs/src/makefiles/pgxs.mk:420: installcheck] Error 1

    $ cat regression.diffs
    diff -U3 /home/joel/postgresql-extensions/pg-telemetry/expected/definitions.out /home/joel/postgresql-extensions/pg-telemetry/results/definitions.out
    --- /home/joel/postgresql-extensions/pg-telemetry/expected/definitions.out	2021-04-26 07:51:30.455845875 +0000
    +++ /home/joel/postgresql-extensions/pg-telemetry/results/definitions.out	2021-04-26 07:51:46.672061123 +0000
    @@ -1,116 +1,79 @@
    set client_min_messages to warning;
    create extension pgtelemetry cascade;
    +ERROR:  column "total_time" does not exist
    select count(*) > 0 from pgtelemetry.database_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.database_size" does not exist
    +LINE 1: select count(*) > 0 from pgtelemetry.database_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.relation_total_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.relation_total_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.relation_total_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.catalog_total_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.catalog_total_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.catalog_total_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.index_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.index_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.index_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.relation_toast_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.relation_toast_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.relation_toast_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.tablespace_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.tablespace_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.tablespace_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.database_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.database_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.database_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.connections_by_application;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.connections_by_application" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.connections_by_applicat...
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.connections_by_state;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.connections_by_state" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.connections_by_state;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.connections_by_ip_source;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.connections_by_ip_source" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.connections_by_ip_sourc...
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.longest_running_active_queries;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.longest_running_active_queries" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.longest_running_active_...
    +                                 ^
    SELECT count(*) > -1 from pgtelemetry.waiting_connections_by_event_type;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.waiting_connections_by_event_type" does not exist
    +LINE 1: SELECT count(*) > -1 from pgtelemetry.waiting_connections_by...
    +                                  ^
    SELECT count(*) > 0 from pgtelemetry.locks_by_type;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.locks_by_type" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.locks_by_type;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.locks_by_mode;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.locks_by_mode" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.locks_by_mode;
    +                                 ^
    SELECT pgtelemetry.count_waiting_on_locks_more_than_seconds(300) >= 0;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  schema "pgtelemetry" does not exist
    +LINE 1: SELECT pgtelemetry.count_waiting_on_locks_more_than_seconds(...
    +               ^
    SELECT count(*) > 0 from pgtelemetry.tuple_access_stats;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.tuple_access_stats" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.tuple_access_stats;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.autovacuum_stats;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.autovacuum_stats" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.autovacuum_stats;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.statement_query_rows_time;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.statement_query_rows_time" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.statement_query_rows_ti...
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.statement_query_buffers;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.statement_query_buffers" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.statement_query_buffers...
    +                                 ^

**Comment by andreasscherbaum** [comment]
Independently I stumbled over the same problem.
The regression test is not loading the extension, will submit a PR and fix that.

**Comment by andreasscherbaum** [comment]
I created #20 to fix this problem.

@joelonsql Can you see if this PR fixes your problem? Thanks!

**Comment by joelonsql** [comment]
Thanks for working on a fix.

I can see a new PostgreSQL instance is now started and that you added "shared_preload_libraries = 'pg_stat_statements'" to extras/regression/postgresql.conf.

However, this does not appear to have fixed the problem:

    $ make installcheck
    /usr/lib/postgresql/13/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/13/bin'    --load-extension=pg_stat_statements --temp-config=extras/regression/postgresql.conf --temp-instance=tmp-regression-test --dbname=contrib_regression definitions
    ============== removing existing temp instance        ==============
    ============== creating temporary instance            ==============
    ============== initializing database system           ==============
    ============== starting postmaster                    ==============
    running on port 64466 with PID 3688
    ============== creating database "contrib_regression" ==============
    CREATE DATABASE
    ALTER DATABASE
    ============== installing pg_stat_statements          ==============
    CREATE EXTENSION
    ============== running regression test queries        ==============
    test definitions                  ... FAILED       23 ms
    ============== shutting down postmaster               ==============

    ======================
    1 of 1 tests failed.
    ======================

    The differences that caused some tests to fail can be viewed in the
    file "/home/joel/postgresql-extensions/pg-telemetry/regression.diffs".  A copy of the test summary that you see
    above is saved in the file "/home/joel/postgresql-extensions/pg-telemetry/regression.out".

    make: *** [/usr/lib/postgresql/13/lib/pgxs/src/makefiles/pgxs.mk:420: installcheck] Error 1

    $ cat regression.diffs
    diff -U3 /home/joel/postgresql-extensions/pg-telemetry/expected/definitions.out /home/joel/postgresql-extensions/pg-telemetry/results/definitions.out
    --- /home/joel/postgresql-extensions/pg-telemetry/expected/definitions.out	2021-04-28 07:05:31.716778574 +0000
    +++ /home/joel/postgresql-extensions/pg-telemetry/results/definitions.out	2021-04-28 07:09:14.550307284 +0000
    @@ -1,116 +1,79 @@
    set client_min_messages to warning;
    create extension pgtelemetry cascade;
    +ERROR:  column "total_time" does not exist
    select count(*) > 0 from pgtelemetry.database_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.database_size" does not exist
    +LINE 1: select count(*) > 0 from pgtelemetry.database_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.relation_total_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.relation_total_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.relation_total_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.catalog_total_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.catalog_total_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.catalog_total_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.index_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.index_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.index_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.relation_toast_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.relation_toast_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.relation_toast_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.tablespace_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.tablespace_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.tablespace_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.database_size;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.database_size" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.database_size;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.connections_by_application;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.connections_by_application" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.connections_by_applicat...
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.connections_by_state;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.connections_by_state" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.connections_by_state;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.connections_by_ip_source;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.connections_by_ip_source" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.connections_by_ip_sourc...
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.longest_running_active_queries;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.longest_running_active_queries" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.longest_running_active_...
    +                                 ^
    SELECT count(*) > -1 from pgtelemetry.waiting_connections_by_event_type;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.waiting_connections_by_event_type" does not exist
    +LINE 1: SELECT count(*) > -1 from pgtelemetry.waiting_connections_by...
    +                                  ^
    SELECT count(*) > 0 from pgtelemetry.locks_by_type;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.locks_by_type" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.locks_by_type;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.locks_by_mode;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.locks_by_mode" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.locks_by_mode;
    +                                 ^
    SELECT pgtelemetry.count_waiting_on_locks_more_than_seconds(300) >= 0;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  schema "pgtelemetry" does not exist
    +LINE 1: SELECT pgtelemetry.count_waiting_on_locks_more_than_seconds(...
    +               ^
    SELECT count(*) > 0 from pgtelemetry.tuple_access_stats;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.tuple_access_stats" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.tuple_access_stats;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.autovacuum_stats;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.autovacuum_stats" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.autovacuum_stats;
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.statement_query_rows_time;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.statement_query_rows_time" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.statement_query_rows_ti...
    +                                 ^
    SELECT count(*) > 0 from pgtelemetry.statement_query_buffers;
    - ?column?
    -----------
    - t
    -(1 row)
    -
    +ERROR:  relation "pgtelemetry.statement_query_buffers" does not exist
    +LINE 1: SELECT count(*) > 0 from pgtelemetry.statement_query_buffers...
    +                                 ^
